### ISSUE TITLE
[jsonConfig schema] several attributes not defined for table elements

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/adapter-react-v5#183]
Admin 6.12.0 reports false positve:

```
snmp has an invalid jsonConfig: [{"instancePath":"/items/oidSets/items/oids/items/0","schemaPath":"#/patternProperties/%5E.%2B/allOf/20/then/properties/items/items/allOf/15/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"attr"},"message":"must NOT have additional properties"},{"instancePath":"/items/oidSets","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
```

Schame seems to be incorrect:
Table elements must have attribute 'attr' to name a table row.

Link to jsonConfig / estimated place of error:
https://github.com/iobroker-community-adapters/ioBroker.snmp/blob/2003d8eb195b00f6286d203760f39594eb7df117/admin/jsonConfig.json#L65

**Comment by ticaki** [comment]
If this is the same scheme used in VS code, all attributes within a table will appear as errors except those that are valid for all.

**Comment by mcm1957** [comment]
@foxriver76 

Issue seems to exist still:

```
snmp has an invalid jsonConfig: [{"instancePath":"/items/oidSets/items/oids/items/0","schemaPath":"#/patternProperties/%5E.%2B/allOf/20/then/properties/items/items/allOf/16/then/allOf/1/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"attr"},"message":"must NOT have additional properties"},{"instancePath":"/items/oidSets","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
```

Tested with snmp Adapter

**Comment by foxriver76** [comment]
Yes unfortunately only webstorm stopped to complain but it needs a more complex solution see my todo comment in https://github.com/ioBroker/adapter-react-v5/pull/190

**Comment by ticaki** [comment]
Doesn't that have to be released first?

**Comment by mcm1957** [comment]
No, as far as I know the adapter accesses the files directly at the web.
Some other errors have been fixed

**Comment by mcm1957** [comment]
> Yes unfortunately only webstorm stopped to complain but it needs a more complex solution see my todo comment in #190

No problem from my side. Until now now issues at adapter have been raised. If some will be raised I will link them to admin / react and explain. So please dont get into excessiv stress. Its only a message not a malfunction. And THANKS for adding the tests at all.

**Comment by mcm1957** [comment]
@foxriver76 
Any reason why this issue is still open?

**Comment by mcm1957** [comment]
defaultSendTo seems to be missing to

```
e3oncan has an invalid jsonConfig: [{"instancePath":"/items/tabUdsDevices/items/tableUdsDevices","schemaPath":"#/patternProperties/%5E.%2B/allOf/23/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"defaultSendTo"},"message":"must NOT have additional properties"},{"instancePath":"/items/tabUdsDevices","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
```

**Comment by foxriver76** [comment]
So from my side no issues known, please report in separate issues if some occur.
