### ISSUE TITLE
[jsonConfig schema] attribute doNotSave missing at password component (and ev. others)

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/adapter-react-v5#192]
Admin reports

```
envertech-pv has an invalid jsonConfig: [{"instancePath":"/items/_cloudPanel/items/cloudPassword","schemaPath":"#/patternProperties/%5E.%2B/allOf/11/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"doNotSave"},"message":"must NOT have additional properties"},{"instancePath":"/items/_cloudPanel","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
```

Attribute doNotSave seems to be missing at component of type 'password'

According to schema.md 'doNOtSave is valid at ALL components.

Link to jsonConfig: https://github.com/iobroker-community-adapters/ioBroker.envertech-pv/blob/1952b7a7a8eb2fded9fb5e857412ca4415a69f1d/admin/jsonConfig.json#L44

@foxriver76

**Comment by foxriver76** [comment]
Yes will adapt it, I only added it to inputs yet, eg a staticLink should not have it or at least it would not make sense

**Comment by mcm1957** [comment]
Ok, thats correct. password is an input type. Well easy to miss one id it must be added at every single component. The schema must be really huge...

nonprior - think that this combination is used really seldom. This adapter does not store the password but only use it for a sendTo to retrieve a token.

**Comment by crycode-de** [comment]
Also missing on `selectSendTo`.

Example: https://github.com/crycode-de/ioBroker.discord/blob/92f0d089940b17af021777384fab4629824d3fe2/admin/jsonConfig.json#L790-L800
