### ISSUE TITLE
add component `accordion` to schema

### ISSUE THREAD

**Issue by foxriver76** [ioBroker/adapter-react-v5#195]
- `accordion` - accordion with items that could be deleted, added, moved up, moved down (Admin 6.6.0 and newer)
    - `items` - `[{"type": see above, "attr": "name", "default": ""}]` - items can be placed like on a `panel` (xs, sm, md, lg and newLine)
    - `titleAttr` - key of the item's list which should be used as name
    - `noDelete` - boolean if delete or add disabled, If `noDelete` is false, add, delete and move up/down should work
    - `clone` - [optional] - if clone button should be shown. If true, the clone button will be shown. If attribute name, this name will be unique.

**Comment by foxriver76** [comment]
as it contains items just like the table, we should fix the table schema first to just apply it to accordion too

**Comment by ticaki** [comment]
any updates?
