### ISSUE TITLE
[jsonConfig schema] attribute "iconPosition" is missing for tabs

### ISSUE THREAD

**Issue by klein0r** [ioBroker/adapter-react-v5#197]
see https://github.com/ioBroker/ioBroker.admin/commit/3838baf001976e6ee7d134350233c45aebb9b9c0

- `tabs` - Tabs with items
  - `items` - Object with panels `{"tab1": {}, "tab2": {}...}`
  - `iconPosition` - `bottom`, `end`, `start` or `top`. Only for panels that has `icon` attribute. Default: `start`

**Comment by klein0r** [comment]
Update: I've used iconPosition on the "tabs" and not on the "panel" element (which is working fine). Is my json incorrect or the schema?

https://github.com/ioBroker/adapter-react-v5/blob/e6899e4cbcfa5924dfc54328ffc492f3d012126a/schemas/jsonConfig.json#L1281-L1299

Example: https://github.com/klein0r/ioBroker.octoprint/blob/22c95d53a571c4bb0d71e7234745f826e7246665/admin/jsonConfig.json#L1-L10

**Comment by foxriver76** [comment]
I think schema is wrong, also https://github.com/ioBroker/ioBroker.admin/blob/master/src/src/components/JsonConfigComponent/SCHEMA.md says it is valid for tabs too

**Comment by foxriver76** [comment]
Does it work code-wise when added at this level as in your example? Then I  can add it to schema as well.

**Comment by klein0r** [comment]
> says it is valid for tabs too

Yes, it works on tabs. But I don't think it works on a panel, because `iconPosition` is never used in the code:

https://github.com/ioBroker/ioBroker.admin/blob/v6.12.6/src/src/components/JsonConfigComponent/ConfigPanel.jsx
