### ISSUE TITLE
[jsonConfig schema] multilingual - uk is missing in 

### ISSUE THREAD

**Issue by klein0r** [ioBroker/adapter-react-v5#198]
```
"params":{"additionalProperty":"uk"},"message":"must NOT have additional properties"}
```

see

https://github.com/ioBroker/adapter-react-v5/blob/33fd97c5ff52226b37e0b3e1982f2dffaf8dc6f4/schemas/jsonConfig.json#L9-L13

**Comment by foxriver76** [comment]
feel free to create the PR from your branch.

**Comment by foxriver76** [comment]
Ops ;-)

then some belated congratulations from my side. An of course priorities are set then *gg*
