### ISSUE TITLE
staticText label and text can be used interchangeable

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/adapter-react-v5#199]
Seit der 6.12.0 bekomme ich folgende Warnung:

`<html>
<body>

admin.0
--
  | 2023-10-28 23:03:10.421	warn	janitza-gridvis has an invalid jsonConfig: [{"instancePath":"/items/mainTab/items/conectionInformation","schemaPath":"#/patternProperties/%5E.%2B/allOf/32/then/required","keyword":"required","params":{"missingProperty":"text"},"message":"must have required property 'text'"},{"instancePath":"/items/mainTab","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

</body>
</html>`

Es sollte doch eigentlich label oder text erlaubt sein.

**Comment by foxriver76** [comment]
Hm ja warum auch immer darf man beides. ;-)

```


staticText - static text like description

    label - multi-language text
    text - same as label

```

**Comment by BenAhrdt** [comment]
Ja. Also eigentlich dürfte er dann nicht meckern.
