### ISSUE TITLE
[jsonConfig schema] textSendTo missing

### ISSUE THREAD

**Issue by crycode-de** [ioBroker/adapter-react-v5#200]
Admin reports
```
ds18b20 has an invalid jsonConfig: [{"instancePath":"/items/remoteTab/items/_remoteConnectedInfo/type","schemaPath":"#/definitions/componentType/enum","keyword":"enum","params":{"allowedValues":["alive","autocomplete","cron","text","number","port","color","checkbox","chips","header","slider","ip","user","room","func","select","icon","image","panel","password","file","sendTo","staticText","custom","pattern","table","instance","language","setState","certificate","certificates","staticImage","staticLink","divider","objectId","selectSendTo","autocompleteSendTo","checkLicense","uuid"]},"message":"must be equal to one of the allowed values"},{"instancePath":"/items/remoteTab","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
```

According to the docs the `textSendTo` type should exists and it's working.

jsonConfig Example:
https://github.com/crycode-de/ioBroker.ds18b20/blob/3b48bdc08b26679dd517e57b6dd344cc0d376fc9/admin/jsonConfig.json#L254-L265

@foxriver76 

Edit:
Also the `"newline": true` parameter is marked as "Property newline is not allowed." in a `textSendTo` field.
Example: https://github.com/crycode-de/ioBroker.discord/blob/92f0d089940b17af021777384fab4629824d3fe2/admin/jsonConfig.json#L597-L607

**Comment by foxriver76** [comment]
I will add the textSendTo, however the property has to be `newLine` with uppercase `L`

**Comment by crycode-de** [comment]
> however the property has to be `newLine` with uppercase `L`

Oh.. thank you! I must have been blind 🙈
