### ISSUE TITLE
type missed.... why

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/adapter-react-v5#203]
in the folowing adapters there is an warning like this:

`2023-10-30 16:43:01.186 - warn: admin.0 (23838) drag-indicator has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"type"},"message":"must have required property 'type'"}]
2023-10-30 16:43:51.786 - warn: admin.0 (23838) bidirectional-counter has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"type"},"message":"must have required property 'type'"}]
2023-10-30 16:44:10.965 - warn: admin.0 (23838) lowpass-filter has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"type"},"message":"must have required property 'type'"}]
2023-10-30 16:44:22.795 - warn: admin.0 (23838) operating-hours has an invalid jsonConfig: [{"instancePath":"","schemaPath":"#/required","keyword":"required","params":{"missingProperty":"type"},"message":"must have required property 'type'"}]`

why? that is the config from bidirectional-counter

`{
    "i18n": true,
    "items":{
        "deleteStatesWithDisable": {
                "type": "checkbox",
                "label": "deleteStateWithDisableText",
                "sm": 6
            },
        "emptyField":{
            "type":"staticText",
            "newLine": true,
            "sm":3
        },
        "infoToCustomConfig": {
            "type": "staticText",
            "label": "infoToCustomConfiglabel",
            "style": {
                "color": "red"
              },
            "sm": 6
        }
    }
 }`

and this is the config from operation-hours
`{
    "i18n": true,
    "items":{
        "informationHeader": {
            "newLine": true,
            "type": "header",
            "text": "mainInformations",
            "sm": 12,
            "size": 3
        },
        "Information1":{
            "newLine":true,
            "type": "staticText",
            "label": "mainInformationText",
            "sm": 6
        },
        "configurationHeader": {
            "newLine": true,
            "type": "header",
            "text": "configuration",
            "sm": 12,
            "size": 3
        },
        "refreshRate": {
            "newLine": true,
            "type": "select",
            "options": [
              {"label":"1 s","value":1000},
              {"label":"2 s","value":2000},
              {"label":"3 s","value":3000},
              {"label":"4 s","value":4000},
              {"label":"5 s","value":5000},
              {"label":"6 s","value":6000},
              {"label":"7 s","value":7000},
              {"label":"8 s","value":8000},
              {"label":"9 s","value":9000},
              {"label":"10 s","value":10000},
              {"label":"20 s","value":20000},
              {"label":"30 s","value":30000},
              {"label":"40 s","value":40000},
              {"label":"50 s","value":50000},
              {"label":"60 s","value":60000}],
              "default": 6000,
            "label": "refreshRate",
            "tooltip": "refreshRateTooltip",
            "sm": 1
        },
        "statesTable":{
            "type":"table",
            "sm":12,
            "allowAddByFilter": true,
            "items":[
                {
                    "type": "text",
                    "attr": "state",
                    "title": "states",
                    "filter": true,
                    "sort": false,
                    "allowAddByFilter": true
                },
                {
                  "type": "cron",
                  "attr": "resetCronJob",
                  "complex": true,
                  "label": "automaticReset",
                  "tooltip": "automaticResetTooltip"
                }
            ]
        }
    }
 }`

i dont know wheres something missed? and where is thze "messege" object?

**Comment by mcm1957** [comment]
@BenAhrdt 
Please add [jsonCOnfig] to subject like other issues.
Please add a linkt to the effected jsonConfig.json - if possible directly to the effected line

**Comment by mcm1957** [comment]
jsonConfig does not contain a type at upmost level.

Nomally either 'type':''tabs' or 'type':'panel' is used. But documentation (https://github.com/BenAhrdt/ioBroker.drag-indicator/blob/a1500b511b50b45d3614ccf21373108a0449fedb/admin/jsonConfig.json#L1) does not clearly state wether one of those types is required or no type at all is allowed too.

@foxriver76 
So this could be an adpater issue OR a schema issue.

**Comment by BenAhrdt** [comment]
@mcm1957 i dont know what i have to do.
Adapter (and Otter Adapters ) works More than one year without changes in config.
Where is some filed „type“ missing?
I dont see it

**Comment by foxriver76** [comment]
Admin will apply a default type but I think we said it is mandatory

**Comment by foxriver76** [comment]
just add `"type": "panel"` at the top level and it should work as expected e.g. like here https://github.com/foxriver76/ioBroker.benchmark/blob/30ec73d85dbe31aab5d1a68b2567eeb3cb47afd9/admin/jsonConfig.json#L2

**Comment by mcm1957** [comment]
Ok, then it should be stated at SCHMA.md

(And for @BenAhrdt to solve the issue: Whats the default? I guess 'panel' but I'm not sure. Please confoirm if time allows)

**Comment by BenAhrdt** [comment]
@foxriver76 i insert it, but there is another warning:

`operating-hours has an invalid jsonConfig: [{"instancePath":"/items/statesTable","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/22/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"allowAddByFilter"},"message":"must NOT have additional properties"}]`

what happens here?

jsonsonfig:
[https://github.com/BenAhrdt/ioBroker.operating-hours/blob/main/admin/jsonConfig.json](https://github.com/BenAhrdt/ioBroker.operating-hours/blob/main/admin/jsonConfig.json)

**Comment by BenAhrdt** [comment]
@foxriver76 if i changed the json config and inset
`"type": "panel"`
at the top level

like this in adapter: opertaion-hours:
`{
    "type": "panel",
    "i18n": true,
    "items":{
        "deleteStatesWithDisable": {
                "type": "checkbox",
                "label": "deleteStateWithDisableText",
                "sm": 6
            },
        "emptyField":{
            "type":"staticText",
            "newLine": true,
            "sm":3
        },
        "infoToCustomConfig": {
            "type": "staticText",
            "label": "infoToCustomConfiglabel",
            "style": {
                "color": "red"
              },
            "sm": 6
        }
    }
 }`


this warning would come
`bidirectional-counter has an invalid jsonConfig: [{"instancePath":"/items/emptyField","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/32/then/oneOf/0/required","keyword":"required","params":{"missingProperty":"text"},"message":"must have required property 'text'"},{"instancePath":"/items/emptyField","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/32/then/oneOf/1/required","keyword":"required","params":{"missingProperty":"label"},"message":"must have required property 'label'"},{"instancePath":"/items/emptyField","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/32/then/oneOf","keyword":"oneOf","params":{"passingSchemas":null},"message":"must match exactly one schema in oneOf"}]`

**Comment by foxriver76** [comment]
I fixed the schema for the operating hours.

However, here is a staticText used without `label` and without `text`.

https://github.com/BenAhrdt/ioBroker.bidirectional-counter/blob/63fea001da4f3aee751e41a4261a08d10665a104/admin/jsonConfig.json#L9 

Thus the schema is complaining. Not sure what you try to achieve here, but in doubt you could try `"text": ""` to mimic the current behavior.

**Comment by BenAhrdt** [comment]
@foxriver76 ok, this was used for have an empty line.
Tomorrow i will have a look in all my adapters and fix the
`"type": "panel"`
then i will have a look at the rest of the warnings
