### ISSUE TITLE
[jsonConfig]: question regarding operating hours jsonConfig

### ISSUE THREAD

**Issue by BenAhrdt** [ioBroker/adapter-react-v5#225]
### No existing issues.

- [X] There is no existing issue for my request.

### Problem location

ioBroker Log

### Warning message

operating-hours has an invalid jsonConfig: [{"instancePath":"/items/statesTable/items/0","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/22/then/properties/items/items/allOf/20/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"allowAddByFilter"},"message":"must NOT have additional properties"}]

### Source link

https://github.com/BenAhrdt/ioBroker.operating-hours/blob/main/admin/jsonConfig.json

### Additional information

What i haveto do, i can not understand the error in the config

**Comment by foxriver76** [comment]
To read the error message, look at the instance path. Here `/items/statesTable/items/0` Follow this path in your config, you will end up at the item at index `0` of the `items` from `statesTable`. Then read the message: `"params":{"additionalProperty":"allowAddByFilter"},"message":"must NOT have additional properties"}]`

So in this item https://github.com/BenAhrdt/ioBroker.operating-hours/blob/aa19bee1afc8bd806e254d118f9a43c3e40363d2/admin/jsonConfig.json#L54-L61 there is a property `allowAddByFilter` which seems to be not allowed. As far as I know this property just is allowed at the table itself.

And please choose an issue title next time.

**Comment by BenAhrdt** [comment]
@foxriver76 OK.
the function allowAddByFilter is alredy not working.
Is this an issue for the admin?

**Comment by foxriver76** [comment]
yes admin

**Comment by BenAhrdt** [comment]
also this:
`janitza-gridvis has an invalid jsonConfig: [{"instancePath":"/items/mainTab/items/projectname","schemaPath":"#/patternProperties/%5E.%2B/allOf/2/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"alsoDependsOn"},"message":"must NOT have additional properties"},{"instancePath":"/items/mainTab","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]`

why does it warn this... i dont know it works fine in the past

**Comment by foxriver76** [comment]
this is probably a bug in the schema + docs, schema was initially created from the docs and there the option is not stated

https://github.com/ioBroker/ioBroker.admin/blob/master/src/src/components/JsonConfigComponent/SCHEMA.md

![grafik](https://github.com/ioBroker/adapter-react-v5/assets/25484431/1411c2ac-b4de-4e3c-9ad8-87bde02cda08)

**Comment by BenAhrdt** [comment]
so i can use this attribut ? without the api does not work, so the attribut works

**Comment by foxriver76** [comment]
yes you can use it, there are still some errors in the schema and this is most likely intended to work. just needs to be added.
