### ISSUE TITLE
[jsonConfig schema] autocompleteSendTo in a table/panel

### ISSUE THREAD

**Issue by ticaki** [ioBroker/adapter-react-v5#226]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

vscode zeigt folgende "Fehler" bei `autocompleteSendTo` in `table` / in `panel`

`table`
- `attr`
- `alsoDependsOn`
- `width`
- `title`

`panel`
- `alsoDependsOn`

`alsoDependsOn - by change of which attributes, the command must be resent`

**Comment by foxriver76** [comment]
thanks for reporting. Will be fixed in a few minutes.

Please use this option for the future json schema issues

![grafik](https://github.com/ioBroker/adapter-react-v5/assets/25484431/e9ff1f2f-85a9-4c6b-b528-dafb6d3be18d)
