### ISSUE TITLE
Schema jsonConfig.json - potentially missing definitions

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/adapter-react-v5#24]
Moved from https://github.com/ioBroker/adapter-react/issues/29 on request of [GermanBluefox](https://github.com/GermanBluefox)
I linked https://raw.githubusercontent.com/ioBroker/adapter-react-v5/master/schemas/jsonConfig.json to vsCode. vsCode reports the errors which seem to be caused by missing definitions in schema:

validatorNoSaveOnError
seems to be missing completly

validator, validatorErrorText, validatorNoSaveOnError
seems to be missing at table elements (item array of table). Validator is working, so the schema seems to be incorrect. As validatorErrorText does not seem to work the schema might be correct - in this case schema.md at admin is incorrect

default, hidden
seem to be missing at table elements (item array of table).

options
seems to be missing at table elements (item array of table) of type "select".

**Comment by mcm1957** [comment]
cloned from https://github.com/ioBroker/adapter-react/issues/29#issuecomment-1100712214

In table items, most (all?) type specific definitions seams to be missing.
E.g. for selectSendTo: command, data, jsonData, defaultFunc, noTranslation are missing.

noMultiEdit is missing completely.

maxLength for type text is missing.

The defaultFunc and onChange object syntax seams to be missing completely. This is used e.g. in linkeddevices [here](https://github.com/Scrounger/ioBroker.linkeddevices/blob/3e5f4833b2db648000dabd696c5d5c3bb50df88f/admin/jsonCustom.json#L18-L23) and [here](https://github.com/Scrounger/ioBroker.linkeddevices/blob/3e5f4833b2db648000dabd696c5d5c3bb50df88f/admin/jsonCustom.json#L53-L60) for example.

**Comment by GermanBluefox** [comment]
What is not possible is to make table in table definitions.

**Comment by mcm1957** [comment]
I still have the following schema mismatches / errors reported by vsCode:

The following tabel attributes are reported as invalid: 
showSecondAddAt

The following attributes of table elements ("items" array) are reported as invalid:
attr
title
filter
sort
validatorErrorText
options
min
max

----

I'm not sure what your last remark refering table in table definitions refers to. I only have one table inside a tab ("tabs" array).

The complete json config raising errors at vsCode can be found here:
https://github.com/mcm1957/ioBroker.snmp/blob/dvp-2.1.x/admin/jsonConfig.json

**Comment by mcm1957** [comment]
This still an open issue

**Comment by foxriver76** [comment]
`jsonEditor` ist also missing

**Comment by mcm1957** [comment]
New 'accordion' element is likely to be missing too

**Comment by foxriver76** [comment]
For the initial `validatorErrorText` is also not working for items, so maybe it is on purpose see https://github.com/ioBroker/ioBroker.admin/issues/1911

**Comment by foxriver76** [comment]
As admin now validates the jsonConfig of every adapter against the schema, it is now crucial that the schema is up-to-date.

Additional it will make sense to validate it in tests https://github.com/ioBroker/testing/issues/583

**Comment by mcm1957** [comment]
@did you test with jsonConfig-demo adapter?
It for sure does not cover all situations - but if some check fail, the schema should be checked.

Which admin version includes the check so that I could test too.
In addition where is the schema taken from - always online from head of master/main?

**Comment by foxriver76** [comment]
Schema always taken from https://github.com/ioBroker/adapter-react-v5/blob/main/schemas/jsonConfig.json

Admin 6.12.0 includes the check whenever an adapter config is opened via browser.

**Comment by MiSchroe** [comment]
"cron" type is missing completely in the schema though it works and is documented at https://github.com/ioBroker/ioBroker.admin/blob/22bd130648ff2754922a91bcdbfad7e9fc278fc3/src/src/components/JsonConfigComponent/SCHEMA.md?plain=1#L263.

**Comment by foxriver76** [comment]
cron has been added now, for the tables we have a separate issue at https://github.com/ioBroker/adapter-react-v5/issues/183

**Comment by foxriver76** [comment]
Please create separate issues if more errors occur
