### ISSUE TITLE
[jsonConfig]:  attribute 'newline' not defined for select

### ISSUE THREAD

**Issue by ticaki** [ioBroker/adapter-react-v5#245]
### No existing issues.

- [X] There is no existing issue for my request.

### Problem location

ioBroker Log

### Warning message

```
reolink has an invalid jsonConfig: [{"instancePath":"/items/_options/items/cameraProtocol","schemaPath":"#/patternProperties/%5E.%2B/allOf/22/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"newline"},"message":"must NOT have additional properties"},{"instancePath":"/items/_options","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
```

### Source link

https://github.com/aendue/ioBroker.reolink/blob/42863bb6bd74194319503b855f95198849577cf9/admin/jsonConfig.json#L17

### Additional information

.

**Comment by foxriver76** [comment]
somehow I have a Déjà-vu.

It should be `newLine` -> uppercase `L`

**Comment by ticaki** [comment]
Sry second time i dont check uppercase. :)

**Comment by foxriver76** [comment]
no problem :smile:
