### ISSUE TITLE
cron definition has wong hour

### ISSUE THREAD

**Issue by arteck** [ioBroker/adapter-react-v5#251]
![grafik](https://github.com/ioBroker/ioBroker.javascript/assets/6681528/97241b11-85c8-42e3-aaad-87067a683cf5)

**Comment by klein0r** [comment]
As far as I know, 24 is not a valid value for hour. 0-23 is the limit.

**Comment by mcm1957** [comment]
Yes 24 is invalid for hour.
We gad thisvissue some time ago and as dar as i know js-controller will reject hour 24 now.

Compinent should allow 90 to 23 for hour onky.
