### ISSUE TITLE
[jsonConfig]: wrong warninmg for password, if use a tableItem

### ISSUE THREAD

**Issue by dirkhe** [ioBroker/adapter-react-v5#292]
### No existing issues.

- [X] There is no existing issue for my request.

### Problem location

ioBroker Log

### Warning message

[
  {
    "instancePath": "/items/_calendars/items/calendars/items/5",
    "schemaPath": "#/definitions/passwordProps/additionalProperties",
    "keyword": "additionalProperties",
    "params": { "additionalProperty": "attr" },
    "message": "must NOT have additional properties"
  },
  {
    "instancePath": "/items/_calendars/items/calendars",
    "schemaPath": "#/patternProperties/%5E.%2B/allOf/23/if",
    "keyword": "if",
    "params": { "failingKeyword": "then" },
    "message": "must match \"then\" schema"
  },
  {
    "instancePath": "/items/_calendars",
    "schemaPath": "#/properties/items/patternProperties/%5E.%2B/allOf/8/if",
    "keyword": "if",
    "params": { "failingKeyword": "then" },
    "message": "must match \"then\" schema"
  }
]

### Source link

-

### Additional information

The UI works as expected, but Schema validation is wrong here.

I get the warning also in IDE:
![image](https://github.com/ioBroker/adapter-react-v5/assets/9537962/bc4dff61-3a81-41dd-8258-9d3c96710118)

here is the json file:

[jsonConfig.json](https://github.com/ioBroker/adapter-react-v5/files/14389278/jsonConfig.json)

for "sendTo" I get also warning for "width" and "title"

**Comment by foxriver76** [comment]
the json config seems to be valid in the meantime
