### ISSUE TITLE
[jsonConfig]: allowDeactivate invalid for object instance

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/adapter-react-v5#308]
### No existing issues.

- [X] There is no existing issue for my request.

### Problem location

IDE

### Warning message

awtrix-light has an invalid jsonConfig: [{"instancePath":"/items/_customApps/items/foreignSettingsInstance","schemaPath":"#/patternProperties/%5E.%2B/allOf/33/then/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"allowDeactivate"},"message":"must NOT have additional properties"},{"instancePath":"/items/_customApps","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match "then" schema"}]

### Source link

https://github.com/klein0r/ioBroker.awtrix-light/blob/master/admin/jsonConfig.json

**Comment by GM-Jokemaster** [comment]
Same here !

**Comment by foxriver76** [comment]
`allowDeactivate`seems to work in tests and also no fail about this from test when checked against awtrix light config
