### ISSUE TITLE
[jsonConfig]: noClearButton gives warning

### ISSUE THREAD

**Issue by tp1de** [ioBroker/adapter-react-v5#337]
### No existing issues.

- [X] There is no existing issue for my request.

### Problem location

ioBroker Log

### Warning message

ems-esp has an invalid jsonConfig: [{"instancePath":"/items/tab-ems-esp/items/emsesp_ip","schemaPath":"#/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"noClearButton"},"message":"must NOT have additional properties"},{"instancePath":"/items/tab-ems-esp/items/emsesp_ip","schemaPath":"#/patternProperties/%5E.%2B/allOf/21/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/tab-ems-esp","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

### Source link

https://github.com/tp1de/ioBroker.ems-esp/blob/main/admin/jsonConfig.json#L18

### Additional information

new attribute in jsonConfig "noClearButton" for text fields added by @GermanBluefox still gives a warning within log.

**Comment by tp1de** [comment]
@foxriver76 any chance to get noClearButton released?

**Comment by mcm1957** [comment]
As this is ONLY a warning which does not effe t the functionality at any way simply ignore it for now. Will be fixed but currently foxriver76 has other priorities (js-controller 6) for sure.

If you can provide a PR feel free to do so.

**Comment by foxriver76** [comment]
Problem is also, that stuff gets added implementation wise and not added to schema or issues are created. Hence, it's hard for me to have an overview and of course hard to keep up at all as json schema in its widely supported draft is a bit messy for some things and would maybe need some considerations before implementing functionality. E. g. this feature recently added https://github.com/ioBroker/ioBroker.admin/blob/master/packages/jsonConfig/SCHEMA.md#includes will take forever to be implemented in the schema.

**Comment by tp1de** [comment]
I do understand, but I was surprised that when @GermanBluefox added the noClearButton attribute very fast, that schema was not adjusted as well.  I am not an IT-guy. I do not know how to change admin / react and provide a PR.

Nevertheless I can stay with materialize for my adapter until jsonConfig works as desired without warnings for end users.

**Comment by foxriver76** [comment]
@tp1de it is now added to the schema
