### ISSUE TITLE
Die Adapter Config wird nicht importiert

### ISSUE THREAD

**Issue by MiRo1310** [ioBroker/adapter-react-v5#350]
### No existing issues.

- [X] There is no existing issue for my problem.

### Description

Wenn ich versuche die Adapter-Config aus einer Datei zu laden, passiert nichts.  Ich habe nachvollziehen können das in der Logo.js in node_modules/@iobroker/adapter-react-v5/components/Logo.js in Zeile 15 evt.target immer null ist, was dazu führt das die Funktion abgebrochen wird.

**Comment by GermanBluefox** [comment]
Was für ein Browser wird dabei verweintet? Unter Chrome/FF kann ich das nicht reproduzieren.

**Comment by MiRo1310** [comment]
Ich benutze auch Chrome. Kann ich sonst noch etwas testen um mehr Rückschlüsse auf den Fehler zu bekommen?

**Comment by MiRo1310** [comment]
Ich habe den Fehler gefunden, und zwar muss target.result duch r.result ersetzt werden, dann geht es. 
![image](https://github.com/user-attachments/assets/c5e3908c-ea01-4417-ab41-864c7199a299)
![image](https://github.com/user-attachments/assets/409ee6c7-eac5-4eb4-84b0-b16eec8d6839)
