### ISSUE TITLE
[jsonConfig]: jsonconfig schema misses "window" attribute for sendTo 

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/adapter-react-v5#355]
### No existing issues.

- [X] There is no existing issue for my request.

### Problem location

ioBroker Log

### Warning message
```
admin.0 | 2024-07-05 17:03:08.874 |
warn |
daikin-cloud has an invalid jsonConfig: [{"instancePath":"/items/_authenticate","schemaPath":"#/definitions/sendToProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"window"},"message":"must NOT have additional properties"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"else"},"message":"must match "else" schema"}]
```
### Source link

https://github.com/Apollon77/ioBroker.daikin-cloud/blob/811486f99fcf062870ba8e9c8a51e2bef507bf9a/admin/jsonConfig.json#L86

### Additional information

https://github.com/ioBroker/ioBroker.admin/issues/2538

**Comment by GermanBluefox** [comment]
`window` is a internal name of the created window, like `_blank` or `_self` or `myName`. So the link will be opened in new window or always in the same tab.
But added
