### ISSUE TITLE
[jsonConfig]: width attribute for tables got lost

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/adapter-react-v5#387]
### No existing issues.

- [X] There is no existing issue for my request.

### Problem location

IDE

### Warning message

node-red has an invalid jsonConfig: [{"instancePath":"/items/_authentication/items/authExt/items/2","schemaPath":"#/items/allOf/36/then/allOf/1/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"width"},"message":"must NOT have additional properties"},{"instancePath":"/items/_authentication/items/authExt","schemaPath":"#/patternProperties/%5E.%2B/allOf/25/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/_authentication","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

### Source link

https://github.com/ioBroker/ioBroker.node-red/blob/9621e2d0e3c023174525c1b73ef0e43b59ad9af5/admin/jsonConfig.json#L319

### Additional information

same problem with iobroker.snmp reproduceable

**Comment by mcm1957** [comment]
@GermanBluefox
@foxriver76 

Problem still exists:

![image](https://github.com/user-attachments/assets/3efbc6d3-7f8e-4d00-8158-2e171d7f9a8e)

Ist the change already published?

**Comment by foxriver76** [comment]
This is another Attribute, unfortunately we cannot change one place for all on tables and need to do for every type

**Comment by mcm1957** [comment]
OK - details:
```
snmp has an invalid jsonConfig: [{"instancePath":"/items/options/items/optChunkSize","schemaPath":"#/definitions/numberProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"width"},"message":"must NOT have additional properties"},{"instancePath":"/items/options","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
```

adapter:
iobroker.snmp

@foxriver76 
Is this Info sufficient and / or shall I open a new Issue?

**Comment by foxriver76** [comment]
It is here https://github.com/iobroker-community-adapters/ioBroker.snmp/blob/ce9c741711f49fb119bdbb64a50214630c3c2404/admin/jsonConfig.json#L406 and it is inside a panel (not a table), I don't think we have a width attribute here.. so the warning seems correct for me @mcm1957
