### ISSUE TITLE
TreeTable when deleting, the delete check icon is missing

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/adapter-react-v5#74]
If you do not use the edit function, but want to use the delete function, no check icon is displayed when deleting.
```jsx
<TreeTable
	columns={treeColumns}
	data={treeData}
	noAdd={true}
	// onUpdate={(newData, oldData) => newTreeData(newData, oldData)}
	onDelete={(newData) => setTreeData(newData)}
/>
```
![Screenshot 2022-11-02 202035](https://user-images.githubusercontent.com/32600934/199587532-2491d6c5-1337-40a9-b991-659b52f54ebf.png)

**Comment by GermanBluefox** [comment]
I think , that if you cannot Add line, so there is no use to delete line. How will you add new lines, when you delete all of them?

**Comment by xXBJXx** [comment]
This is then meant in such a way that if NoAdd and noEdit is active that the table shows only things which were generated over the adapter e.g., Device which are queried.
But if you don't need a device, you should be able to delete it from the adapter.

**Comment by GermanBluefox** [comment]
> This is then meant in such a way that if NoAdd and noEdit is active that the table shows only things which were generated over the adapter e.g., Device which are queried. But if you don't need a device, you should be able to delete it from the adapter.

But in this case, the adapter will add the device again by next start. I think you need something like "ignore" checkbox.
